SUPERCHROMEPATH = "C:\\Program Files (x86)\\Fianium\\SuperChrome\\SuperChrome.exe"
MFCCCDPATH = "C:\\Program Files (x86)\\Jobin Yvon\\SDK\\Examples\\C++\\CCD\\Release\\MFC_CCDExample.exe"
CCDMONOPATH = "C:\\Program Files (x86)\\Jobin Yvon\\SDK\\Examples\\C++\\Mono\\Release\\MonoExample.exe"
SPFIIIDIR = "C:\\SpfIII\\"
KINESISSTAGEMOTORID = 27502401
KINESISSTAGEMAXLIMIT = 1200000
KINESISSTAGEMINLIMIT = 0
KINESISMFFID = 37856267
EPSRATIO = 0.05#パワーの許容誤差比率．(1.0±epsratio)*目標パワーの範囲で許容する
SHUTTERCOMPORT = 'COM5'
PRIORCOMPORT = 'COM3'